[tool.poetry]
name = "qs"
version = "0.1.0"
description = "Opalsite deployment for local flask sites"
authors = ["Steve Holden <steve@holdenweb.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7 || ^3.8 || ^3.9 || ^3.10 || ^3.11"
jinja2 = "^3.1.2"
fabric = "^3.0.0"
mongoengine = "^0.27.0"
opalstack = "^1.0.1"

[tool.poetry.scripts]
qs = "qs:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
