#!/bin/bash
export PYTHONPATH=$HOME/apps/{{PROJECT}}/myapp
PIDFILE="$HOME/apps/{{PROJECT}}/tmp/{{PROJECT}}.pid"
if [ -e "${PIDFILE}" ] && (ps -u $(whoami) -opid= |
                           grep -P "^\s*$(cat ${PIDFILE})$" &> /dev/null); then
  echo "Already running."
  exit 99
fi
echo -n 'Started at '
date "+%Y-%m-%d %H:%M:%S"
/home/sholden/apps/{{PROJECT}}/env/bin/uwsgi --ini /home/sholden/apps/{{PROJECT}}/uwsgi.ini
