#!/bin/bash
export PYTHONPATH=$(pwd)/myapp
PIDFILE="$HOME/apps/{{TARGET}}/tmp/{{TARGET}}.pid"
if [ -e "${PIDFILE}" ] && (ps -u $(whoami) -opid= |
                           grep -P "^\s*$(cat ${PIDFILE})$" &> /dev/null); then
  echo "Already running."
  exit 99
fi
echo -n 'Started at '
date "+%Y-%m-%d %H:%M:%S"
/home/sholden/apps/{{TARGET}}/env/bin/uwsgi --ini /home/sholden/apps/{{TARGET}}/uwsgi.ini
