#!/bin/bash
source ~/.ssh/env
APPHOME=$HOME/apps/{{PROJECT}}
export PYTHONPATH=${APPHOME}/src
PIDFILE="${APPHOME}/tmp/{{PROJECT}}.pid"
{% block content %}
echo "$0: This file does nothing"
{% endblock %}