[uwsgi]
master = True
http-socket = 127.0.0.1:{{PORT_NO}}
virtualenv = {{HOME_DIR}}/apps/{{PROJECT}}/.venv/
daemonize = {{HOME_DIR}}/logs/apps/{{PROJECT}}/uwsgi.log
pidfile = {{HOME_DIR}}/apps/{{PROJECT}}/tmp/{{PROJECT}}.pid
workers = 2
threads = 2

# adjust the following to point to your project
wsgi-file = {{HOME_DIR}}/apps/{{PROJECT}}/wsgi.py
touch-reload = {{HOME_DIR}}/apps/{{PROJECT}}/wsgi.py
